# -*- coding: utf-8 -*-
"""
Created on Sun Feb  3 14:22:57 2019

@author: leo
"""

import numpy as np
import pandas as pd
import sys
import re
import random
import datetime
import datetime
import calendar
from os import mkdir
main_path = "D:/learning/Arash/war_participants/articles/infobox/"
try:
    mkdir(main_path)
except FileExistsError:
    pass
writer=pd.read_csv(main_path+'input/infobox_new.csv') 



#################################commander1
info_commander=writer.loc[:,['wid','title','tmp']]
def function0(a,b):
    if a!=0:
        return a
    else:
        return b
info_commander['commander']=info_commander['tmp'].str.extract(r'commander3(.*)',expand=False)

info_commander['comb1_2']=info_commander['commander'].str.extract(r'(.*?)commander[123456]',expand=False)
info_commander=info_commander.fillna(0)
info_commander['commander']=info_commander.apply(lambda x: function0(x.comb1_2,x.commander), axis=1)
info_commander.drop('comb1_2',axis=1, inplace=True)

info_commander['comb1_2']=info_commander['commander'].str.extract(r'(.*?)combatant',expand=False)
info_commander=info_commander.fillna(0)
info_commander['commander']=info_commander.apply(lambda x: function0(x.comb1_2,x.commander), axis=1)
info_commander.drop('comb1_2',axis=1, inplace=True)


info_commander['comb1_2']=info_commander['commander'].str.extract(r'(.*?)strength',expand=False)
info_commander=info_commander.fillna(0)
info_commander['commander']=info_commander.apply(lambda x: function0(x.comb1_2,x.commander), axis=1)
info_commander.drop('comb1_2',axis=1, inplace=True)


info_commander['comb1_2']=info_commander['commander'].str.extract(r'(.*?)casualties',expand=False)
info_commander=info_commander.fillna(0)
info_commander['commander']=info_commander.apply(lambda x: function0(x.comb1_2,x.commander), axis=1)
info_commander.drop('comb1_2',axis=1, inplace=True)

info_commander['comb1_2']=info_commander['commander'].str.extract(r'(.*?)campaignbox',expand=False)
info_commander=info_commander.fillna(0)
info_commander['commander']=info_commander.apply(lambda x: function0(x.comb1_2,x.commander), axis=1)
info_commander.drop('comb1_2',axis=1, inplace=True)

info_commander['comb1_2']=info_commander['commander'].str.extract(r'(.*?)units *[123456]',expand=False)
info_commander=info_commander.fillna(0)
info_commander['commander']=info_commander.apply(lambda x: function0(x.comb1_2,x.commander), axis=1)
info_commander.drop('comb1_2',axis=1, inplace=True)

info_commander['comb1_2']=info_commander['commander'].str.extract(r'(.*?)conflict=',expand=False)
info_commander=info_commander.fillna(0)
info_commander['commander']=info_commander.apply(lambda x: function0(x.comb1_2,x.commander), axis=1)
info_commander.drop('comb1_2',axis=1, inplace=True)

info_commander['comb1_2']=info_commander['commander'].str.extract(r'(.*?)formations[12345678]',expand=False)
info_commander=info_commander.fillna(0)
info_commander['commander']=info_commander.apply(lambda x: function0(x.comb1_2,x.commander), axis=1)
info_commander.drop('comb1_2',axis=1, inplace=True)



info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('*', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('<br>', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('<br/>', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('<br />', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('<br / >', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('<hr>', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('\{\{br\}\}', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('<br/ >', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('(?<=\]) *\| *(?=\[)', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('(?<=\]) *\| *(?=\{)', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('(?<=\}) *\| *(?=\[)', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('(?<=\}) *\| *(?=\{)', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('\| *(?=\{)', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('\| *(?=\[)', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('----', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('<hr/>a\)', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('<hr/>b\)', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('<hr/>c\)', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('<hr/>d\)', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)

info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('\{\{-\}\}', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)

info_commander=info_commander.drop('commander', axis=1).join(info_commander['commander'].str.split('\| *\d{1,2} *=', expand=True).stack().reset_index(level=1, drop=True).rename('commander'))
info_commander.drop_duplicates(inplace=True)

info_commander.drop_duplicates(inplace=True)
info_commander=info_commander.reset_index(drop=True)




info_commander=info_commander.fillna(0)
missing=info_commander[info_commander['commander']==0]
info_commander=info_commander[info_commander['commander']!=0]

info_commander['commander']=info_commander['commander'].str.strip()
info_commander['commander']=info_commander['commander'].str.replace(r"'''",'')
info_commander['commander']=info_commander['commander'].str.replace(r'\{\{efn\|.*?\}\}','')
info_commander['commander']=info_commander['commander'].str.replace(r'\{\{sfn\|.*?\}\}','')
info_commander['commander']=info_commander['commander'].str.replace(r'\{\{refn\|.*?\}\}','')


info_commander['commander']=info_commander['commander'].str.replace(r'<ref.*?>.*?</ref>','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[ *file:.*?\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'<small.*?>.*?</small>','')
info_commander['commander']=info_commander['commander'].str.replace(r'\{\{cite web\|.*?\}\}','')
info_commander['commander']=info_commander['commander'].str.strip()
info_commander['image']=info_commander['commander'].str.extract(r'\[\[image:(.*?)\]\]',expand=False)
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[image:.*?\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\{\{small\|.*?\}\}','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[mraf\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[tsar\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lord\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[sir\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[qing dynasty\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'<!--.*?-->','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[list of.*?\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\(.*?\)','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[death by natural causes.*?]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[death by natural causes.*?\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[.*?\|†\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[.*?\|#\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[madame\|m<sup>me</sup>\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[.*?\|ⱶ\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[.*?\|\+\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[captain \|naval captain\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[general officer\|gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major general\|majgen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major general\|maj\.gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant-general\|lt.gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant general\|lt.gen\]\]','')

info_commander['commander']=info_commander['commander'].str.replace(r'\[\[admiral\|adm\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[admiral \|adm\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[admiral\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[rear admiral\]\]','')

info_commander['commander']=info_commander['commander'].str.replace(r'\[\[commander\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[general\]\]','')

info_commander['commander']=info_commander['commander'].str.replace(r'\[\[general \|gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[general \|gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[grand master  \|grand master\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[captain \|capt\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[president of the united states\|president\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[vice admiral\|vadm\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[maj\. gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brig\. gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\{\{#tag:.*?\}\}','')
info_commander['commander']=info_commander['commander'].str.replace(r':\{\{.*','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[holy league \|holy league\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[navy\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[2nd belorussian front\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[1st ukrainian front\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[ii corps \|ii corps\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[iii corps \|iii corps\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[iv corps \|iv corps\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[meiji emperor\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[general\|gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lt\. gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant general\|lt\. gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[commander \|cdr\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[sub-lieutenant\|sub-lt\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[befehlshaber der u-boote\|bdu\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[tan son nhut\|det\. 15\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[tbd\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\{\{collapsible list.*?\}\}','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[military leadership in the american civil war#the union\|and others\.\.\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[llandaff\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[sheriff\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[marshal of france\|maréchal\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[wounded in action\|\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[prince regent\|prince-regent\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[prime minister of the imperial cabinet\|prime minister\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[high commissioners for palestine and transjordan\|high commissioner\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[commander-in-chief\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[air commodore\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[haganah\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[air chief marshal\|acm\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[colonel\|col\.\]\]','')

info_commander['commander']=info_commander['commander'].str.replace(r'\[\[commanding officer\|co\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[governor general of india\|gov\. gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[prime minister of india|pm\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[air marshal\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant general\|lt\. gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major general\|maj\.gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[maharaja of jammu and kashmir\|maharaja\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant colonel\|lt\. col\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brevet \|bvt\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[leader of the opposition \|leader of the opposition\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[captain general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[hassan uprising\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[general\|gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[air marshal\|am\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[vice-admiral\|adm\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major\|maj\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[group captain\|gp capt\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[consul\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant general、|lt\.gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major general\|maj\. gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[grand hetman of lithuania\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[vice admiral\|v\.adm\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant-general \|lt-gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[captain \|captain\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[general officer\|general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[roman consul\|consul\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[vice-admiral\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[papal\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[mercenarie\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[cavalry\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major-general \|mg\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brigadier-general \|bg\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brigadier general\|brig\. gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[marshal of poland\|marshal\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[field marshal \|field marshal\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[colonel general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[doctor \|dr\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[bishop of clogher \|lord bishop of clogher\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[ghazi \|gazi\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major-general \|major general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[prime minister of bangladesh\|premier\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[rhondda\|glyn rhondda\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[vice admiral\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[colonel\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[imam\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[commander\|cdr\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[earl of carrick\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[maj gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[field crown hetman\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[voivode\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brig\. gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[rulers of moldavia\|voivode of moldavia\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[khan \|khan\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[president of france|president\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brigadier general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[group captain\|gp\.capt\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[air marshal\|air mshl\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[executed by hanging\|☠\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[counter admiral\|\'\'contre-amiral\'\'\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant-general\|ltg\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[colonel\|col\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lt\. colonel\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[regional command south\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major-general\|mgen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brigadier-general\|bgen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[count of flanders\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[prisoner of war\|p\.o\.w\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lt\. general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[maj\. general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brigadier\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[maha vir chakra\|mvc\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[shah\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant-colonel\|lt\.col\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[grand hetman\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[regimentarz\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[hetmans of ukrainian cossacks\|hetman\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant-general\|lgen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brig\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brigadier\|brig\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[admiral \|admiral\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[†\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[air vice-marshal\|avm\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[counter admiral\|.*?\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major general \|major general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[theme \|thema\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[byzantine navy\|fleets\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[group captain|gp capt\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[wing commander \|wg cdr\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant colonel\|lt col\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[high king\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[mouse\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[al-qassim province\|qassim region\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[commodore \|commodore\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[governor-general of the dutch east indies\|governor-general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[korvettenkapitän\|kkpt\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[maj\. general\|maj\. gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lt\. general\|lt\. gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brig\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[col\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[transylvania\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[general officer commanding\|goc\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[24th infantry division \|24th infantry division\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major-general\|mg\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brigadier-general\|b\.gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[imperial commissioner \|imperial commissioner\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[jiangsu\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[viceroy of huguang\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[common era\|ce\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[gov\. liu rong\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[mayor of the palace\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[hms castor \|hms \'\'castor\'\'\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[hms north star \|\'\'hms north star\'\'\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[hms calliope \|\'\'hms calliope\'\'\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[hms elphinstone\|heics \'\'elphinstone\'\'\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[islamic republican party\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[maj\. gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant-general\|lgen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[air marshal\|air-mshl\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major-general\|mgen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brigadier|brig\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[maharashtra police\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[commander \|cdr\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant-general\|ltg\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brigadier-general\|bgen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[political resident\|p\/a\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant colonel\|lt\.col\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant colonel\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[first lieutenant\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[ban of slavonia\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[rnvr\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[oberstleutnant\|otl\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major general\|maj\. gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[military cross\|mc\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[mullah\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major-general\|m\.gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[rear-admiral\|radm]\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[admiral\|adm\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant-general \|lt\. gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant-general \|lt gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[vice admiral\|vice adm\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[air vice-marshal\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[rear admiral \|rear admiral\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[maréchal-des-logis\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[quartermaster sergeant\|sergent-fourrier\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[corporal\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant \|lieutenant\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[provost of edinburgh\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[prime minister\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[general field marshal\|gfm\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[grand vizier\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brigade general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[admiral|adm.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[ranks in the french navy#officiers généraux — flag officers\|adm\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[governor\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[indian army\|ia\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[ban \|ban\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[kapitänleutnant\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[senior superintendent of police\|ssp\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[sindh police\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[inspector general\|ig sindh\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[additional inspector general of police\|aig\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major-general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[standing nato maritime group 1\|standing nato maritime group one\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[commodore \|cdre\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[field marshal\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant\|lt\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant-general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major-general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'title = \[\[','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[prime minister of pakistan\|prime minister\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[chief of army staff \|army chief\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[chairman joint chiefs of staff committee\|chairman jcsc\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[inter-services intelligence\|isi\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[chief of naval staff \|naval chief\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[air mshl\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lt\. gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[colonel \|col\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[contre-amiral\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant general\|lieutenant general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[kapitänleutnant\|kl\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[count of barcelona\|count\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[south wales borderers\|24th of foot\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[president of bangladesh\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[cibyrrhaeots\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[chief of air staff \|air chief\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[international freedom battalion\|ifb\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[communist party of turkey\/marxist–leninist\|tkp\/ml\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[field marshal\|fm\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[field marshal\|fm\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[military leadership in the american civil war#the confederacy\|and others\.\.\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[prince\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[state of vietnam\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[army group centre\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[jiang \|general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[grand pensionary\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[daimyō\|lord\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[w:zh:.*?\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[colonel general\|generaloberst\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[general officer\|gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major general\|mgen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[vice-admiral\|vadm\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[rear-admiral\|radm\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[air vice marshal\|avm\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[air commodore\|air cdre\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[governor general of pakistan\|gov\. gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant colonel\|col\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant colonel\|lieutenant colone\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[divisional general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant colonel\|lieutenant colonel\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r' of \[\[.*?\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\,','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant colonel\|ltn-col\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[archduke\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[master-general of the ordnance\|mgo\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[col\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[giritli hüseyin pasha\|hussein\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[commodore |contre-amiral\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[republic of venice\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[grand duchy of tuscany\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[duchy of modena and reggio\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[mercenary\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[modena\|modenese\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[high duke of poland\|duke\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[prime minister of poland\|prime minister\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[marshal\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[army general \|general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[sultan\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[mosu\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[halab|aleppo\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[colonel \|colonel\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[viceroy\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[commandant-general\|commandant-general\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[constable of castile\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[#revolt of february 1522\|1522 revolt\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[sardar\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[flight lieutenant\|flt\. lt.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[wing commander \|wing commander\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[captain \|cpt\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[bač, serbia\|bács\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[ras \|ras\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[rear-admiral\|rear admiral\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[hetmans of polish-lithuanian commonwealth\|hetman\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major general \|maj\. gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant-general\|lit\. gen\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[:wikt:ông\|ông\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[:wikt:thượng thư\|thượng thư\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\|notes      = a: .*','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[jarl in sweden\|jarl\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[ghent\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[mawlawi \|maulvi\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[grand prince of the hungarians\|grand prince\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[italian co-belligerent army\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[air chief marshal\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[fakir\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[great crown hetman\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[horka \|horka\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[prince of orange\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[khagan\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[toqui\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[rear-admiral\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[earl\|jarl\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lt\. col\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant\|lt\.\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[commander\|cdr\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[four star general\|gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[four-star admiral\|adm\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[lieutenant-general\|gen\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[brigadeführer\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[war in the vendée\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[peshwa\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[monarch\|king\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[bey\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[a\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[b\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[c\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[d\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[battle of vistula lagoon\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[pow\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[bey\|beg\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[bishop\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[army of the danube\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[guangzhou\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'<\/ref>.*','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[flag lieutenant\|flag-lieut\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[ss-ogruf\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[commandant \|commandant\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[commandant\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[major \|maj\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[saint-lô\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[france\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[obergruppenführer\|ss-ogruf\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[governor of worcester\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[co-belligerence\|co-belligerent\]\]','')
info_commander['commander']=info_commander['commander'].str.replace(r'\[\[kingdom of georgia\]\]','')
info_commander['commander']=info_commander['commander'].str.strip()



####whether there are more than 2 middle brackets in a cell
info_commander['brackets']=info_commander['commander'].str.extract(r'\[\[(.*?)\]\].*?\[\[',expand=False)
info_commander=info_commander.fillna(0)
info_commander_nob=info_commander[info_commander['brackets']==0]
brackets=info_commander[info_commander['brackets']!=0]

brackets_infobox = pd.DataFrame(columns=('wid','title','tmp','commander','image'))
brackets=brackets.fillna(0)
rcount=0

for row in brackets.iterrows():
    #print(row[1][0])
    rcount=rcount+1
    print(rcount)
   
    if row[1][3]==0:
        brackets_infobox=brackets_infobox.append(pd.DataFrame({'wid':[row[1][0]],'title':[row[1][1]],'tmp':[row[1][2]],'commander':[row[1][3]],'image':[0]}),ignore_index=True) 
    if row[1][3]!=0:
        counter=0
        text=''
        sm=0
        for c in row[1][3]:
            
            
            if c=='[':
                counter=counter+1
               
            if c==']':
                counter=counter-1
                sm=sm+1
                
            if counter>0:
                text=text+c
                
            if counter==0 and sm>0:
                text=text+c
                brackets_infobox=brackets_infobox.append(pd.DataFrame({'wid':[row[1][0]],'title':[row[1][1]],'tmp':[row[1][2]],'commander':[text],'image':[0]}),ignore_index=True)
                text=''
                sm=0
                
info_commander_nob.drop('brackets',axis=1, inplace=True)
info_commander=info_commander_nob.append(brackets_infobox)
info_commander=info_commander.reset_index(drop=True)
info_commander['linked']=info_commander['commander'].str.extract(r'\[\[(.*?)\]\]',expand=False)
info_commander=info_commander.fillna(0)
info_commander=info_commander[info_commander['linked']!=0]

info_commander['country']=info_commander['commander'].str.extract(r'\{\{(.*?)\}\} *\[\[',expand=False)

info_commander=info_commander.fillna(0)

df2=info_commander['country'].str.split('}}',expand=True)
df2=df2.fillna(0)

info_commander=info_commander.drop('country',axis=1).join(df2)
info_commander.rename(columns={0:'commander_of_1',1:'commander_of_2'},inplace=True)
info_commander['commander_of_1']=info_commander['commander_of_1'].str.replace(r'\{\{','')
info_commander['commander_of_2']=info_commander['commander_of_2'].str.replace(r'\{\{','')
info_commander['commander_of_1']=info_commander['commander_of_1'].str.replace(r'\}\}','')
info_commander['commander_of_2']=info_commander['commander_of_2'].str.replace(r'\}\}','')

info_commander=info_commander.fillna(0)

info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.extract(r'(.*(?=\.svg\|)|.*(?=\.png\|)|.*(?=\.jpg\|))',expand=False)
info_commander['image']=info_commander['image'].str.replace(r'_',' ')
info_commander['image']=info_commander['image'].str.replace(r'flag of','')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'vexilloid of the','')
info_commander['image']=info_commander['image'].str.replace('\(.*?\)','')
info_commander['image']=info_commander['image'].str.replace('\d','')
info_commander['image']=info_commander['image'].str.replace(r'-','')
info_commander['image']=info_commander['image'].str.replace(r'coat of','')
info_commander['image']=info_commander['image'].str.replace(r'royal arms of','')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'arms of','')
info_commander['image']=info_commander['image'].str.replace(r'naval jack  stars','')
info_commander['image']=info_commander['image'].str.replace(r'the republic of the rif','rif republic')
info_commander['image']=info_commander['image'].str.replace(r'^the','')
info_commander['image']=info_commander['image'].str.replace(r'naval ensign of','')
info_commander['image']=info_commander['image'].replace('red flag',0)
info_commander['image']=info_commander['image'].str.replace(r'flag','')
info_commander['image']=info_commander['image'].str.replace(r'philippine revolution  magdalo','philippine')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'coa$','')
info_commander['image']=info_commander['image'].str.replace(r'th century','')
info_commander['image']=info_commander['image'].str.replace(r'banner of arms','')
info_commander['image']=info_commander['image'].str.replace(r'army','')
info_commander['image']=info_commander['image'].str.replace(r'arms','')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'former','')
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].replace(r'socialist red',0)
info_commander['image']=info_commander['image'].replace(r'm',0)
info_commander['image']=info_commander['image'].replace(r'a ppp','ppp')

info_commander['image']=info_commander['image'].str.replace(r'naval jack of the','')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'pre$','')
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'^green harp','')
info_commander['image']=info_commander['image'].replace(r'splanasir','spla-nasir')
info_commander['image']=info_commander['image'].str.replace(r'^asafia','')
info_commander['image']=info_commander['image'].replace(r'philippine revolution  kkk','philippine')
info_commander['image']=info_commander['image'].str.replace(r'alternative$','')
info_commander['image']=info_commander['image'].replace(r'black',0)
info_commander['image']=info_commander['image'].replace(r'white',0)
info_commander['image']=info_commander['image'].replace(r'ounr','oun-r')
info_commander['image']=info_commander['image'].replace(r'united states forces&nbsp;– iraq','united states')
info_commander['image']=info_commander['image'].replace(r'bandera cntait','bandera cnt-ait')
info_commander['image']=info_commander['image'].replace(r'afrikanerweerstandsbeweging','afrikaner-weerstandsbeweging')
info_commander['image']=info_commander['image'].replace(r'alqaeda','al-qaeda')
info_commander['image']=info_commander['image'].replace(r'pakistani','pakistan')
info_commander['image']=info_commander['image'].str.replace(r'used model$','')
info_commander['image']=info_commander['image'].str.replace(r'^ancient  ','')
info_commander['image']=info_commander['image'].str.replace(r'^state  ','')
info_commander['image']=info_commander['image'].str.replace(r'asymmetric','')
info_commander['image']=info_commander['image'].replace(r'byzantine imperial ,','byzantine empire')
info_commander['image']=info_commander['image'].str.replace(r',$','')
info_commander['image']=info_commander['image'].str.replace(r'alislam','al-islam')
info_commander['image']=info_commander['image'].str.replace(r"people's liberation   the",'')
info_commander['image']=info_commander['image'].str.replace(r"naval jack of",'')
info_commander['image']=info_commander['image'].replace(r'icon image',0)
info_commander['image']=info_commander['image'].replace(r'infoboxhez',0)
info_commander['image']=info_commander['image'].replace(r'\|size=px',0)
info_commander['image']=info_commander['image'].replace('',0)
info_commander['image']=info_commander['image'].replace(r'philippine alternate','philippine')
info_commander['image']=info_commander['image'].replace(r'war  the imperial japanese','japan')
info_commander['image']=info_commander['image'].replace(r'lesser   the kingdom of bohemia','kingdom of bohemia')
info_commander['image']=info_commander['image'].str.replace(r'logo of the','')
info_commander['image']=info_commander['image'].str.strip()
info_commander['image']=info_commander['image'].str.replace(r'^the','')
info_commander['image']=info_commander['image'].str.replace(r', small, based on palavestra','')
info_commander['image']=info_commander['image'].str.replace(r'civil and  france','france')
info_commander['image']=info_commander['image'].str.replace(r'chinese red','china')
info_commander['image']=info_commander['image'].str.replace(r'中國工農紅軍軍旗','china')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)

image=info_commander[info_commander['image']!=0]

info_commander['commander_of_1']=info_commander.apply(lambda x: function0(x.image,x.commander_of_1), axis=1)
info_commander.drop('image',axis=1, inplace=True)

info_commander['linked']=info_commander['linked'].str.replace(r'\|.*','')

#######clean commander_of_1
info_commander['image']=info_commander['commander_of_1'].str.extract(r'(flagicon *image.*)',expand=False)
info_commander=info_commander.fillna(0)

info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'\.svg.*','')
info_commander['image']=info_commander['image'].str.replace(r'\.png.*','')
info_commander['image']=info_commander['image'].str.replace(r'\.jpg.*','')
info_commander['image']=info_commander['image'].str.replace(r'\.gif.*','')
info_commander['image']=info_commander['image'].str.replace(r'flagicon image *\|','')
info_commander['image']=info_commander['image'].str.replace(r'_',' ')
info_commander['image']=info_commander['image'].str.replace(r'flag of','')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'vexilloid of the','')
info_commander['image']=info_commander['image'].str.replace('\(.*?\)','')
info_commander['image']=info_commander['image'].str.replace('\d','')
info_commander['image']=info_commander['image'].str.replace(r'-','')
info_commander['image']=info_commander['image'].str.replace(r'coat of','')
info_commander['image']=info_commander['image'].str.replace(r'royal arms of','')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'arms of','')
info_commander['image']=info_commander['image'].str.replace(r'naval jack  stars','')
info_commander['image']=info_commander['image'].str.replace(r'the republic of the rif','rif republic')
info_commander['image']=info_commander['image'].str.replace(r'^the','')
info_commander['image']=info_commander['image'].str.replace(r'naval ensign of','')
info_commander['image']=info_commander['image'].replace('red flag',0)
info_commander['image']=info_commander['image'].replace('red flag.svg',0)
info_commander['image']=info_commander['image'].str.replace(r'flag','')
info_commander['image']=info_commander['image'].str.replace(r'philippine revolution  magdalo','philippine')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'coa$','')
info_commander['image']=info_commander['image'].str.replace(r'th century','')
info_commander['image']=info_commander['image'].str.replace(r'banner of arms','')
info_commander['image']=info_commander['image'].str.replace(r'army','')
info_commander['image']=info_commander['image'].str.replace(r'arms','')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)


info_commander['image']=info_commander['image'].str.replace(r'former','')
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].replace(r'socialist red',0)
info_commander['image']=info_commander['image'].replace(r'm',0)
info_commander['image']=info_commander['image'].replace(r'a ppp','ppp')

info_commander['image']=info_commander['image'].str.replace(r'naval jack of the','')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'pre$','')
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'^green harp','')
info_commander['image']=info_commander['image'].replace(r'splanasir','spla-nasir')
info_commander['image']=info_commander['image'].str.replace(r'^asafia','')
info_commander['image']=info_commander['image'].replace(r'philippine revolution  kkk','philippine')
info_commander['image']=info_commander['image'].str.replace(r'alternative$','')
info_commander['image']=info_commander['image'].replace(r'black',0)
info_commander['image']=info_commander['image'].replace(r'white',0)
info_commander['image']=info_commander['image'].replace(r'ounr','oun-r')
info_commander['image']=info_commander['image'].replace(r'united states forces&nbsp;– iraq','united states')
info_commander['image']=info_commander['image'].replace(r'bandera cntait','bandera cnt-ait')
info_commander['image']=info_commander['image'].replace(r'afrikanerweerstandsbeweging','afrikaner-weerstandsbeweging')
info_commander['image']=info_commander['image'].replace(r'alqaeda','al-qaeda')
info_commander['image']=info_commander['image'].replace(r'pakistani','pakistan')
info_commander['image']=info_commander['image'].str.replace(r'used model$','')
info_commander['image']=info_commander['image'].str.replace(r'^ancient  ','')
info_commander['image']=info_commander['image'].str.replace(r'^state  ','')
info_commander['image']=info_commander['image'].str.replace(r'asymmetric','')
info_commander['image']=info_commander['image'].replace(r'byzantine imperial ,','byzantine empire')
info_commander['image']=info_commander['image'].str.replace(r',$','')
info_commander['image']=info_commander['image'].str.replace(r'alislam','al-islam')
info_commander['image']=info_commander['image'].str.replace(r"people's liberation   the",'')
info_commander['image']=info_commander['image'].str.replace(r"naval jack of",'')
info_commander['image']=info_commander['image'].replace(r'icon image',0)
info_commander['image']=info_commander['image'].replace(r'infoboxhez',0)
info_commander['image']=info_commander['image'].replace(r'\|size=px',0)
info_commander['image']=info_commander['image'].replace('',0)
info_commander['image']=info_commander['image'].replace(r'philippine alternate','philippine')
info_commander['image']=info_commander['image'].str.replace(r'logo of the','')
info_commander['image']=info_commander['image'].replace(r'war  the imperial japanese','japan')
info_commander['image']=info_commander['image'].replace(r'lesser   the kingdom of bohemia','kingdom of bohemia')
info_commander['image']=info_commander['image'].str.strip()
info_commander['image']=info_commander['image'].str.replace(r'^the','')
info_commander['image']=info_commander['image'].str.replace(r', small, based on palavestra','')
info_commander['image']=info_commander['image'].str.replace(r'civil and  france','france')
info_commander['image']=info_commander['image'].str.replace(r'chinese red','china')
info_commander['image']=info_commander['image'].str.replace(r'中國工農紅軍軍旗','china')
info_commander['image']=info_commander['image'].str.replace(r'naval jack  stripes','')
info_commander['image']=info_commander['image'].str.replace(r'president of','')
info_commander['image']=info_commander['image'].str.replace(r'logo of','')
info_commander['image']=info_commander['image'].str.replace(r'governorgeneral of','')
info_commander['image']=info_commander['image'].str.replace(r'prime minister of','') 
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)


command_image=info_commander[info_commander['image']!=0]

info_commander['commander_of_1']=info_commander.apply(lambda x: function0(x.image,x.commander_of_1), axis=1)
info_commander.drop('image',axis=1, inplace=True)
info_commander['commander_of_1']=info_commander['commander_of_1'].str.replace(r'^.*?\|','')
info_commander['commander_of_1']=info_commander['commander_of_1'].str.replace(r'\|.*','')
info_commander=info_commander.fillna(0)

#######clean commander_of_2
info_commander['image']=info_commander['commander_of_2'].str.extract(r'(flagicon *image.*)',expand=False)
info_commander=info_commander.fillna(0)

info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'\.svg.*','')
info_commander['image']=info_commander['image'].str.replace(r'\.png.*','')
info_commander['image']=info_commander['image'].str.replace(r'\.jpg.*','')
info_commander['image']=info_commander['image'].str.replace(r'\.gif.*','')
info_commander['image']=info_commander['image'].str.replace(r'flagicon image *\|','')
info_commander['image']=info_commander['image'].str.replace(r'_',' ')
info_commander['image']=info_commander['image'].str.replace(r'flag of','')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'vexilloid of the','')
info_commander['image']=info_commander['image'].str.replace('\(.*?\)','')
info_commander['image']=info_commander['image'].str.replace('\d','')
info_commander['image']=info_commander['image'].str.replace(r'-','')
info_commander['image']=info_commander['image'].str.replace(r'coat of','')
info_commander['image']=info_commander['image'].str.replace(r'royal arms of','')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'arms of','')
info_commander['image']=info_commander['image'].str.replace(r'naval jack  stars','')
info_commander['image']=info_commander['image'].str.replace(r'the republic of the rif','rif republic')
info_commander['image']=info_commander['image'].str.replace(r'^the','')
info_commander['image']=info_commander['image'].str.replace(r'naval ensign of','')
info_commander['image']=info_commander['image'].replace('red flag',0)
info_commander['image']=info_commander['image'].str.replace(r'flag','')
info_commander['image']=info_commander['image'].str.replace(r'philippine revolution  magdalo','philippine')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'coa$','')
info_commander['image']=info_commander['image'].str.replace(r'th century','')
info_commander['image']=info_commander['image'].str.replace(r'banner of arms','')
info_commander['image']=info_commander['image'].str.replace(r'army','')
info_commander['image']=info_commander['image'].str.replace(r'arms','')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)


info_commander['image']=info_commander['image'].str.replace(r'former','')
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].replace(r'socialist red',0)
info_commander['image']=info_commander['image'].replace(r'm',0)
info_commander['image']=info_commander['image'].replace(r'a ppp','ppp')

info_commander['image']=info_commander['image'].str.replace(r'naval jack of the','')
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'pre$','')
info_commander=info_commander.fillna(0)
info_commander['image']=info_commander['image'].str.replace(r'^green harp','')
info_commander['image']=info_commander['image'].replace(r'splanasir','spla-nasir')
info_commander['image']=info_commander['image'].str.replace(r'^asafia','')
info_commander['image']=info_commander['image'].replace(r'philippine revolution  kkk','philippine')
info_commander['image']=info_commander['image'].str.replace(r'alternative$','')
info_commander['image']=info_commander['image'].replace(r'black',0)
info_commander['image']=info_commander['image'].replace(r'white',0)
info_commander['image']=info_commander['image'].replace(r'ounr','oun-r')
info_commander['image']=info_commander['image'].replace(r'united states forces&nbsp;– iraq','united states')
info_commander['image']=info_commander['image'].replace(r'bandera cntait','bandera cnt-ait')
info_commander['image']=info_commander['image'].replace(r'afrikanerweerstandsbeweging','afrikaner-weerstandsbeweging')
info_commander['image']=info_commander['image'].replace(r'alqaeda','al-qaeda')
info_commander['image']=info_commander['image'].replace(r'pakistani','pakistan')
info_commander['image']=info_commander['image'].str.replace(r'used model$','')
info_commander['image']=info_commander['image'].str.replace(r'^ancient  ','')
info_commander['image']=info_commander['image'].str.replace(r'^state  ','')
info_commander['image']=info_commander['image'].str.replace(r'asymmetric','')
info_commander['image']=info_commander['image'].replace(r'byzantine imperial ,','byzantine empire')
info_commander['image']=info_commander['image'].str.replace(r',$','')
info_commander['image']=info_commander['image'].str.replace(r'alislam','al-islam')
info_commander['image']=info_commander['image'].str.replace(r"people's liberation   the",'')
info_commander['image']=info_commander['image'].str.replace(r"naval jack of",'')
info_commander['image']=info_commander['image'].replace(r'icon image',0)
info_commander['image']=info_commander['image'].replace(r'infoboxhez',0)
info_commander['image']=info_commander['image'].replace(r'\|size=px',0)
info_commander['image']=info_commander['image'].replace('',0)
info_commander['image']=info_commander['image'].replace(r'philippine alternate','philippine')
info_commander['image']=info_commander['image'].str.replace(r'logo of the','')
info_commander['image']=info_commander['image'].replace(r'war  the imperial japanese','japan')
info_commander['image']=info_commander['image'].replace(r'lesser   the kingdom of bohemia','kingdom of bohemia')
info_commander['image']=info_commander['image'].str.strip()
info_commander['image']=info_commander['image'].str.replace(r'^the','')
info_commander['image']=info_commander['image'].str.replace(r', small, based on palavestra','')
info_commander['image']=info_commander['image'].str.replace(r'civil and  france','france')
info_commander['image']=info_commander['image'].str.replace(r'chinese red','china')
info_commander['image']=info_commander['image'].str.replace(r'中國工農紅軍軍旗','china')
info_commander['image']=info_commander['image'].str.replace(r'naval jack  stripes','')
info_commander['image']=info_commander['image'].str.replace(r'president of','')
info_commander['image']=info_commander['image'].str.replace(r'logo of','')
info_commander['image']=info_commander['image'].str.replace(r'governorgeneral of','')
info_commander['image']=info_commander['image'].str.replace(r'prime minister of','') 
info_commander['image']=info_commander['image'].str.strip()
info_commander=info_commander.fillna(0)


command_image=info_commander[info_commander['image']!=0]

info_commander['commander_of_2']=info_commander.apply(lambda x: function0(x.image,x.commander_of_2), axis=1)
info_commander.drop('image',axis=1, inplace=True)
info_commander['commander_of_2']=info_commander['commander_of_2'].str.replace(r'^.*?\|','')
info_commander['commander_of_2']=info_commander['commander_of_2'].str.replace(r'\|.*','')
info_commander=info_commander.fillna(0)


commander3_infobox=info_commander.loc[:,['wid','title','linked','commander_of_1','commander_of_2']]
commander3_infobox.rename(columns={'linked':'commander'},inplace=True)
commander3_infobox['commander_of_3']=0
commander3_infobox['commander_of_4']=0
commander3_infobox['side']=3
commander3_infobox['commander_of_1']=commander3_infobox['commander_of_1'].replace('red flag.svg',0)
commander3_infobox.to_csv(main_path+'output/commander3_infobox.csv',index=False)
